---
  deployment:
    task:
      - export DEPLOYPATH=/home/smkbandung/python_app/karyaseru/
      - /bin/cp -r blog $DEPLOYPATH
      - /bin/cp -r templates $DEPLOYPATH
      - /bin/cp -r homepage $DEPLOYPATH
      - /bin/cp -r dashboard $DEPLOYPATH
      - /bin/cp requirements.txt $DEPLOYPATH
      - source /home/smkbandung/virtualenv/python_app/karyaseru/3.7/bin/activate && cd /home/smkbandung/python_app/karyaseru
      - python manage.py collectstatic --noinput
      - python manage.py migrate