# Generated by Django 3.2.7 on 2021-09-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Judul Post (Karya)')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(upload_to='post/images/', verbose_name='Gambar/Photo')),
                ('body', models.TextField(verbose_name='Konten')),
                ('ig_account', models.CharField(help_text='Isi dengan link instagram author.', max_length=100, verbose_name='Instagram Account')),
                ('category', models.ManyToManyField(to='blog.Category')),
            ],
        ),
    ]
