# Generated by Django 3.2.7 on 2021-09-03 08:14

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(null=True),
        ),
    ]
