# Generated by Django 3.2.7 on 2021-09-25 07:03

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210906_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='verfied',
            field=models.BooleanField(default=False, verbose_name='Terverivikasi'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Penulis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='blog.Category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(null=True, verbose_name='Konten/Tulisan'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ig_account',
            field=models.CharField(help_text='Isi dengan link instagram author.', max_length=100, verbose_name='Akun Instagram'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='media/post/images/', verbose_name='Gambar/Photo'),
        ),
    ]
