# Generated by Django 3.2.7 on 2021-09-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210925_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post/images/', verbose_name='Gambar/Photo'),
        ),
    ]
