# Generated by Django 3.2.7 on 2021-09-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='verfied',
            new_name='verified',
        ),
    ]
