# Generated by Django 3.2.7 on 2021-09-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_verfied_post_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ig_account',
            field=models.CharField(help_text='Isi dengan link instagram penulis.', max_length=100, verbose_name='Akun Instagram'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Gambar/Photo'),
        ),
    ]
