# Generated by Django 3.2.7 on 2021-10-08 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'svg', 'gif', 'bmp'])], verbose_name='Icon Kategory'),
        ),
    ]
