# Generated by Django 3.2.7 on 2021-10-08 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(null=True, upload_to='category_icon/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg', 'png', 'svg', 'gif', 'bmp'])], verbose_name='Icon Kategory'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, help_text='Untuk Slug jangan diisi (otomatis oleh sistem).', null=True),
        ),
    ]
