# Generated by Django 3.2.7 on 2021-10-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_post_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='v_yt_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
