# Generated by Django 3.2.7 on 2021-10-28 06:11

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_v_yt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100, verbose_name='Pemilik Karya'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(null=True, verbose_name='Penjelasan Karya'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Gambar/Cover Karya'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, max_length=70, verbose_name='Nama Karya'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.URLField(blank=True, help_text='Masukan link video jika ada, untuk disematkan di artikel.', null=True, verbose_name='Link Video Youtube'),
        ),
    ]
