# Generated by Django 3.2.7 on 2021-11-26 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=100, verbose_name='Nama Lengkap')),
                ('ig_account', models.CharField(max_length=100, verbose_name='Link Akun Instagram')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, help_text='Isi jika memang karya yang di-unggah adalah karya ilmiah. Berformat pdf', null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Karya Tulis Ilmiah'),
        ),
    ]
