# Generated by Django 3.2.7 on 2021-11-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ig_account',
            field=models.CharField(db_index=True, help_text='Masukan username instagram kalian (tanpa @), untuk di sematkan di Karya.', max_length=100, unique=True, verbose_name='Username Instagram'),
        ),
    ]
