# Generated by Django 3.2.7 on 2021-11-29 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_author_ig_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='ig_account',
            field=models.CharField(db_index=True, help_text='Masukan username instagram kalian (tanpa @)', max_length=100, unique=True, verbose_name='Username Instagram'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ManyToManyField(null=True, to='blog.Author', verbose_name='Pemilik Karya'),
        ),
    ]
