# Generated by Django 3.2.7 on 2021-11-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20211129_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ManyToManyField(to='blog.Author', verbose_name='Pemilik Karya'),
        ),
    ]
