# Generated by Django 3.2.7 on 2021-09-25 07:43

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=100, verbose_name='Slogan')),
                ('expl', django_quill.fields.QuillField(verbose_name='Penjelasan Karyaseru')),
            ],
        ),
    ]
